# This file is part of Invenio-Client.
# Copyright (C) 2014, 2015 CERN.
#
# Invenio-Client is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio-Client is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "pypy"

matrix:
  allow_failures:
    - python: pypy

install:
  - pip install --upgrade pip
  - pip install check-manifest coveralls pydocstyle
  - pip install pytest pytest-pep8 pytest-cov pytest-cache
  - pip install -e .[docs,tests]

script:
  - "check-manifest --ignore .travis-\\*-requirements.txt"
  - sphinx-build -qnNW docs docs/_build/html
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false
